application: second-pier-741
version: 1
runtime: php
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: test.php
  
env_variables:
 DEVELOPMENT_DB_HOST: ''
 DEVELOPMENT_DB_USERNAME: 'root'
 DEVELOPMENT_DB_PASSWORD: ''
 DEVELOPMENT_DB_NAME: 'guestbook'
 PRODUCTION_CLOUD_SQL_INSTANCE: '/cloudsql/guestbook:my-cloudsql-instance'
 PRODUCTION_DB_USERNAME: ''
 PRODUCTION_DB_PASSWORD: ''
 PRODUCTION_DB_NAME: 'guestbook'
